<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;win64-realse</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SocketApplication\SocketSTD\MessageApp - 副本.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LJC.NetCoreFrameWork.Net\LJC.NetCoreFrameWork.Net.csproj" />
  </ItemGroup>

</Project>
